# Generated by Django 2.2.11 on 2020-04-06 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_info',
            fields=[
                ('questionNo', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='密保问题编号')),
                ('question', models.CharField(max_length=30, verbose_name='密保问题')),
            ],
            options={
                'db_table': 'question_info',
            },
        ),
        migrations.CreateModel(
            name='Tec_info',
            fields=[
                ('teacherNo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('tecPassword', models.CharField(max_length=12, verbose_name='密码')),
                ('answer', models.CharField(max_length=30, verbose_name='密保答案')),
                ('tecState', models.BooleanField(verbose_name='状态')),
                ('questionNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear.Question_info')),
            ],
            options={
                'db_table': 'tec_info',
            },
        ),
        migrations.CreateModel(
            name='Stu_info',
            fields=[
                ('studentNo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('stuPassword', models.CharField(max_length=12, verbose_name='密码')),
                ('answer', models.CharField(max_length=30, verbose_name='密保答案')),
                ('stuState', models.BooleanField(verbose_name='状态')),
                ('questionNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bear.Question_info')),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
    ]
